apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-health-dashboard
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-health-dashboard
  template:
    metadata:
      labels:
        app: cluster-health-dashboard
    spec:
      serviceAccountName: webapp-sa
      containers:
        - name: app
          image: k8s-security-lab/vulnerable-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-health-dashboard
  namespace: default
spec:
  selector:
    app: cluster-health-dashboard
  ports:
    - port: 5000
      targetPort: 5000
